version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "${NEO4J_BROWSER_PORT}:7474"  # веб-интерфейс
      - "${NEO4J_BOLT_PORT}:7687"     # Bolt-протокол
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  mongo_data:
  redis_data:
  neo4j_data:
  neo4j_logs: